# Pull base image (based on debian:bookworm-slim and python3)
FROM python:3-slim-bookworm

# UID and GID default to sudo user, overridden in docker-compose.yml or with -e flag
ARG UID=0
ARG GID=0

# Update the package list, install sudo, create a project_name user, and grant password-less sudo permissions
RUN apt update && \
    apt install -y sudo && \
    addgroup --gid $GID project_name && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" project_name && \
    echo 'project_name ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /project_name

# Copy project and install dependencies
COPY . .
RUN chown -R project_name /project_name
RUN pip install -r requirements.txt

RUN mkhomedir_helper project_name
USER project_name

RUN bash -c "cat aliases.sh >> ~/.bashrc"
